Description: AWS VPC

Parameters:
  VpcCidrBlock:
    Description: The VPC CIDR block
    Type: String

  PrimaryPublicSubnetCidrBlock:
    Description: The Pimary Public Subnet CIDR block
    Type: String

  SecondaryPublicSubnetCidrBlock:
    Description: The Secondary Public Subnet CIDR block
    Type: String

  PrimaryAppSubnetCidrBlock:
    Description: The Pimary App Subnet CIDR block
    Type: String

  SecondaryAppSubnetCidrBlock:
    Description: The Secondary App Subnet CIDR block
    Type: String

  PrimaryBackendSubnetCidrBlock:
    Description: The Pimary Backend Subnet CIDR block
    Type: String

  SecondaryBackendSubnetCidrBlock:
    Description: The Secondary Backend Subnet CIDR block
    Type: String

  NatGateway:
    Description: Set if you want to use a NAT Gateway
    Type: String
    Default: ""

Conditions:
  CreateNatGateway: !Not [!Equals [!Ref NatGateway, ""]]

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  Ipv6VpcCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref Vpc
    DependsOn:
      - Vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: Vpc
      InternetGatewayId:
        Ref: InternetGateway
    DependsOn:
      - Vpc
      - InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public
    DependsOn:
      - Vpc

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
    DependsOn:
      - InternetGateway
      - PublicRouteTable

  PrimaryPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref PrimaryPublicSubnetCidrBlock
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-primary
    DependsOn:
      - Vpc

  PrimaryPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PrimaryPublicSubnet
    DependsOn:
      - PublicRoute
      - PrimaryPublicSubnet

  SecondaryPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref SecondaryPublicSubnetCidrBlock
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-secondary
    DependsOn:
      - Vpc

  SecondaryPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SecondaryPublicSubnet
    DependsOn:
      - PublicRouteTable
      - SecondaryPublicSubnet

  PrimaryAppElasticIp:
    Type: AWS::EC2::EIP
    Condition: CreateNatGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat-primary

  PrimaryAppNatGateway:
    Type: AWS::EC2::NatGateway
    Condition: CreateNatGateway
    Properties:
      AllocationId: !GetAtt PrimaryAppElasticIp.AllocationId
      SubnetId: !Ref PrimaryPublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat-primary
    DependsOn:
      - PrimaryPublicSubnet
      - PrimaryAppElasticIp

  PrimaryAppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-app-primary
    DependsOn:
      - Vpc

  PrimaryAppRoute:
    Type: AWS::EC2::Route
    Condition: CreateNatGateway
    Properties:
      NatGatewayId: !Ref PrimaryAppNatGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrimaryAppRouteTable
    DependsOn:
      - PrimaryAppNatGateway
      - PrimaryAppRouteTable

  PrimaryAppSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref PrimaryAppSubnetCidrBlock
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-app-primary
    DependsOn:
      - Vpc

  PrimaryAppSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrimaryAppRouteTable
      SubnetId: !Ref PrimaryAppSubnet
    DependsOn:
      - PrimaryAppRouteTable
      - PrimaryAppSubnet

  SecondaryAppElasticIp:
    Type: AWS::EC2::EIP
    Condition: CreateNatGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat-secondary

  SecondaryAppNatGateway:
    Type: AWS::EC2::NatGateway
    Condition: CreateNatGateway
    Properties:
      AllocationId: !GetAtt SecondaryAppElasticIp.AllocationId
      SubnetId: !Ref SecondaryPublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat-secondary
    DependsOn:
      - SecondaryPublicSubnet
      - SecondaryAppElasticIp

  SecondaryAppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-app-secondary
    DependsOn:
      - Vpc

  SecondaryAppRoute:
    Type: AWS::EC2::Route
    Condition: CreateNatGateway
    Properties:
      NatGatewayId: !Ref SecondaryAppNatGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref SecondaryAppRouteTable
    DependsOn:
      - SecondaryAppNatGateway
      - SecondaryAppRouteTable

  SecondaryAppSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref SecondaryAppSubnetCidrBlock
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-app-secondary
    DependsOn:
      - Vpc

  SecondaryAppSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecondaryAppRouteTable
      SubnetId: !Ref SecondaryAppSubnet
    DependsOn:
      - SecondaryAppRouteTable
      - SecondaryAppSubnet

  BackendRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-backend
    DependsOn:
      - Vpc

  PrimaryBackendSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref PrimaryBackendSubnetCidrBlock
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-backend-primary
    DependsOn:
      - Vpc

  PrimaryBackendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BackendRouteTable
      SubnetId: !Ref PrimaryBackendSubnet
    DependsOn:
      - BackendRouteTable
      - PrimaryBackendSubnet

  SecondaryBackendSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref Vpc
      CidrBlock: !Ref SecondaryBackendSubnetCidrBlock
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-backend-secondary
    DependsOn:
      - Vpc

  SecondaryBackendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BackendRouteTable
      SubnetId: !Ref SecondaryBackendSubnet
    DependsOn:
      - BackendRouteTable
      - SecondaryBackendSubnet

  S3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      VpcId: !Ref Vpc
      RouteTableIds:
        - !Ref PublicRouteTable
        - !Ref PrimaryAppRouteTable
        - !Ref SecondaryAppRouteTable
        - !Ref BackendRouteTable
    DependsOn:
      - Vpc
      - PublicRouteTable
      - PrimaryAppRouteTable
      - SecondaryAppRouteTable
      - BackendRouteTable

  SsmSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: SSM Endpoint
      GroupName: SsmEndpoint
      SecurityGroupIngress: 
        - IpProtocol: tcp
          CidrIp: !GetAtt Vpc.CidrBlock
          FromPort: 443
          ToPort: 443
        - IpProtocol: tcp
          CidrIpv6: !Select [0, !GetAtt Vpc.Ipv6CidrBlocks]
          FromPort: 443
          ToPort: 443
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ssm-endpoint
      VpcId: !Ref Vpc
    DependsOn:
      - Vpc
      - Ipv6VpcCidrBlock

  SsmVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      VpcId: !Ref Vpc
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SsmSecurityGroup
      SubnetIds:
        - !Ref PrimaryAppSubnet
        - !Ref SecondaryAppSubnet
    DependsOn:
      - Vpc
      - SsmSecurityGroup
      - PrimaryAppSubnet
      - SecondaryAppSubnet

Outputs:
  Vpc:
    Description: The VPC ID
    Value: !Ref Vpc

  SsmEndpointHostedZone:
    Description: SSM service interface endpoint hosted zone
    Value: !Select [0, !Split [":", !Select [0, !GetAtt SsmVpcEndpoint.DnsEntries]]]

  SsmEndpoint:
    Description: SSM service interface endpoint DNS name
    Value: !Select [1, !Split [":", !Select [0, !GetAtt SsmVpcEndpoint.DnsEntries]]]
